steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/scraper-heavy', './services/scraper-heavy']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scraper-heavy']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'scraper-heavy'
  - '--image'
  - 'gcr.io/$PROJECT_ID/scraper-heavy'
  - '--region'
  - 'asia-south1'
  - '--memory'
  - '2Gi'

options:
  logging: CLOUD_LOGGING_ONLY
