steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/lead-pipeline-main', './services/pipeline-main']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/lead-pipeline-main']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'lead-pipeline-main'
  - '--image'
  - 'gcr.io/$PROJECT_ID/lead-pipeline-main'
  - '--region'
  - 'asia-south1'
  - '--memory'
  - '256Mi'
